animations:
  ax-battler:
    type: DMA
    animation-table-address: 0x3A350
    animation-index: 0
    animation-count: 31
    dma-frame-table-address: 0x4492E
    tile-data-addresses:
      - 0x44B98
    bounds-table-address: 0x399AA
    palette-address: 0x38492
  tyris-flare:
    type: DMA
    animation-table-address: 0x3D41A
    animation-index: 0
    animation-count: 31
    dma-frame-table-address: 0x60570
    tile-data-addresses:
      - 0x607A6
    bounds-table-address: 0x399AA
    palette-address: 0x38492
  gilius-thunderhead:
    type: DMA
    animation-table-address: 0x3BCB0
    animation-index: 0
    animation-count: 31
    dma-frame-table-address: 0x4FB58
    tile-data-addresses:
      - 0x4FDA2
    bounds-table-address: 0x399AA
    palette-address: 0x38492
  amazon:
    type: DMA
    animation-table-address: 0x790D2
    animation-index: 0
    animation-count: 28
    dma-frame-table-address: 0x7A08E
    tile-data-addresses:
      - 0x7A25A
    tile-data-compressed: true
    bounds-table-address: 0x40262
    palette-address: 0x38B10
maps:
  wilderness:
    address: 0x15D8
    base-y-table-address: 0x879E
  turtle-village:
    address: 0x161A
    base-y-table-address: 0x87A4
  main-land-coast:
    address: 0x1664
    base-y-table-address: 0x87C2
    custom-entity-trigger-lists:
      - name: beginner-mode
        address: 0x37ACC
  fiends-path:
    address: 0x16A6
    base-y-table-address: 0x87CC
  eagles-head:
    address: 0x16F0
    base-y-table-address: 0x87D2
  death-adders-castle:
    address: 0x1732
    base-y-table-address: 0x87DC
  dungeons:
    address: 0x1784
    base-y-table-address: 0x87E6
  death-bringers-lair:
    address: 0x17C6
    base-y-table-address: 0x8804
    custom-entity-load-group-addresses:
      - 0x38308
      - 0x38316
  duel:
    address: 0x182C
    base-y-table-address: 0
  ending:
    address: 0x1876
    base-y-table-address: 0
  demo1:
    address: 0x18C0
    base-y-table-address: 0x879E
