animations:
  ax-battler:
    type: DMA
    animation-table-address: 0x3A350
    animation-index: 0
    animation-count: 31
    dma-frame-table-address: 0x4492E
    tile-data-addresses:
      - 0x44B98
    bounds-table-address: 0x399AA
    palette-address: 0x38492
  tyris-flare:
    type: DMA
    animation-table-address: 0x3D41A
    animation-index: 0
    animation-count: 31
    dma-frame-table-address: 0x60570
    tile-data-addresses:
      - 0x607A6
    bounds-table-address: 0x399AA
    palette-address: 0x38492
  gilius-thunderhead:
    type: DMA
    animation-table-address: 0x3BCB0
    animation-index: 0
    animation-count: 31
    dma-frame-table-address: 0x4FB58
    tile-data-addresses:
      - 0x4FDA2
    bounds-table-address: 0x399AA
    palette-address: 0x38492
  heninger:
    type: DMA
    animation-table-address: 0x43656
    animation-index: 0
    animation-count: 28
    dma-frame-table-address: 0x69166
    tile-data-addresses:
      - 0x69340
    bounds-table-address: 0x40262
    palette-address: 0x38B54
  longmoan:
    type: DMA
    animation-table-address: 0x71F72
    animation-index: 0
    animation-count: 28
    dma-frame-table-address: 0x6D5E0
    tile-data-addresses:
      - 0x6D772
    bounds-table-address: 0x40262
    palette-address: 0x38B54
  amazon:
    type: DMA
    animation-table-address: 0x790D2
    animation-index: 0
    animation-count: 28
    dma-frame-table-address: 0x7A08E
    tile-data-addresses:
      - 0x7A25A
    tile-data-compressed: true
    bounds-table-address: 0x40262
    palette-address: 0x38B10
  skeleton:
    type: DMA
    animation-table-address: 0x3ED06
    animation-index: 0
    animation-count: 21
    dma-frame-table-address: 0x59A42
    tile-data-addresses:
      - 0x59BEC
    bounds-table-address: 0x40262
    palette-address: 0x38492
  bad-brother:
    type: PRE_LOADED
    animation-table-address: 0x737AE
    animation-index: 0
    animation-count: 13
    tile-data-addresses:
      - 0x7532A
    bounds-table-address: 0x40262
    palette-address: 0x38A88
  death-adder:
    type: PRE_LOADED
    animation-table-address: 0x74192
    animation-index: 0
    animation-count: 11 # Actually 12 animations but the last one is Death Bringer sitting which had custom tile loading
    tile-data-addresses:
      - 0x7532A
      - 0x77D6E
    bounds-table-address: 0x40262
    palette-address: 0x38BDC
  death-bringer-sitting:
    type: PRE_LOADED
    animation-table-address: 0x74192
    animation-index: 11
    animation-count: 1
    tile-data-addresses:
      - 0x74B76
    bounds-table-address: 0x40262
    palette-address: 0x38C20
  death_adder_specials:
    type: PRE_LOADED
    animation-table-address: 0x5FB2C
    animation-index: 0
    animation-count: 3
    tile-data-addresses:
      - 0x5FC2A
    bounds-table-address: 0x40262
    palette-address: 0x5FC08
  lt_bitter:
    type: PRE_LOADED
    animation-table-address: 0x7C718
    animation-index: 0
    animation-count: 10
    tile-data-addresses:
      - 0x7D088
    bounds-table-address: 0x40262
    palette-address: 0x38B54
  chicken_leg:
    type: PRE_LOADED
    animation-table-address: 0x4086A
    animation-index: 0
    animation-count: 5
    tile-data-addresses:
      - 0x40E8A
    bounds-table-address: 0x40262
    palette-address: 0x38ACC
  dragon:
    type: PRE_LOADED
    animation-table-address: 0x41B16
    animation-index: 0
    animation-count: 5
    tile-data-addresses:
      - 0x420FE
    bounds-table-address: 0x40262
    palette-address: 0x38ACC
  blue_dragon_flame:
    type: PRE_LOADED
    animation-table-address: 0x41B3E
    animation-index: 0
    animation-count: 1
    tile-data-addresses:
      - 0x420FE
    bounds-table-address: 0x40262
    palette-address: 0x38ACC
  red_dragon_fire_ball:
    type: PRE_LOADED
    animation-table-address: 0x41B46
    animation-index: 0
    animation-count: 2
    tile-data-addresses:
      - 0x420FE
    bounds-table-address: 0x40262
    palette-address: 0x38ACC
  villager:
    type: PRE_LOADED
    animation-table-address: 0x5FFD0
    animation-index: 0
    animation-count: 2
    tile-data-addresses:
      - 0x60096
    bounds-table-address: 0x40262
    palette-address: 0x38492
  thief:
    type: PRE_LOADED
    animation-table-address: 0x731F2
    animation-index: 0
    animation-count: 4
    tile-data-addresses:
      - 0x733EA
    bounds-table-address: 0x3A192
    palette-address: 0x38492
maps:
  wilderness:
    address: 0x15D8
    base-y-table-address: 0x879E
  turtle-village:
    address: 0x161A
    base-y-table-address: 0x87A4
  main-land-coast:
    address: 0x1664
    base-y-table-address: 0x87C2
    custom-entity-trigger-lists:
      - name: beginner-mode
        address: 0x37ACC
  fiends-path:
    address: 0x16A6
    base-y-table-address: 0x87CC
  eagles-head:
    address: 0x16F0
    base-y-table-address: 0x87D2
  death-adders-castle:
    address: 0x1732
    base-y-table-address: 0x87DC
  dungeons:
    address: 0x1784
    base-y-table-address: 0x87E6
  death-bringers-lair:
    address: 0x17C6
    base-y-table-address: 0x8804
    custom-entity-load-group-addresses:
      - 0x38308
      - 0x38316
  duel:
    address: 0x182C
    base-y-table-address: 0
  ending:
    address: 0x1876
    base-y-table-address: 0
  demo1:
    address: 0x18C0
    base-y-table-address: 0x879E
